name = "reelscore"
compatibility_date = "2025-03-19"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "reelscore-db"
database_id = "c7810fd5-3d57-477e-8320-5b1676661572"

[[kv_namespaces]]
binding = "SCORE_CACHE"
id = "f02c7b82491b4223b58f9be5bedb09d2"
